### ISSUE TITLE
pause screen stops working properly

### ISSUE THREAD

**Issue by ScrabRider** [LeeMoriya/Warp#3]
when i have this mod activated, pausing doesn't pause the game, the menu doesn't appear, and i can't "unpause". the only way i know to fix it is to quit and deactivate the mod. is there some part of setup that i missed? whats going on?

**Comment by LeeMoriya** [comment]
The current version of the game (shown in the top left of the OPTIONS menu) is v1.9.07b. Make sure you're using that version.
